Service Worker Support
jacksonrayhamilton/bundlifier pull request #1
Opened 2018-07-07 06:41 UTC by jacksonrayhamilton

@caleb531, let me know what you think.

2018-07-19 02:16 UTC, caleb531 requested changes

2018-07-19 02:16 UTC, caleb531 commented on SwGenerator.mjs
> +  var match = aPath.match(/(.+?)\//, '');
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match), `match` doesn't accept a second argument like `replace` does. ;)

But I would consider using `aPath.split(path.sep)` instead—it doesn't require a regex, and it's platform-agnostic.

2018-07-19 02:16 UTC, caleb531 commented on SwGenerator.mjs
> +    var swDir = sw.dir || path.dirname(first(values(es)));
You've already computed `first(values(es))` as `jsBundle`.

2018-07-19 02:16 UTC, caleb531 commented on SwGenerator.mjs
> +        return RuntimeCaching(new RegExp(pattern), 'cacheFirst');
Re: `new RegExp(pattern)` – Your configuration file is JS, not JSON, so you could surely allow the user to supply regex literals rather than regexes as strings. What was your reasoning for the latter?

2019-01-03 02:18 UTC, jacksonrayhamilton commented on SwGenerator.mjs
> +  var match = aPath.match(/(.+?)\//, '');
Good idea, I decided to use `split`.

2019-01-03 02:18 UTC, jacksonrayhamilton commented on SwGenerator.mjs
> +    var swDir = sw.dir || path.dirname(first(values(es)));
Thanks for catching that.

2019-01-03 02:18 UTC, jacksonrayhamilton commented on SwGenerator.mjs
> +        return RuntimeCaching(new RegExp(pattern), 'cacheFirst');
Actually, the configuration file _is_ JSON.

2019-01-03 02:20 UTC, jacksonrayhamilton commented
Thanks for reviewing this Caleb.  Almost forgot about it!

2019-01-03 02:20 UTC, merged